### ISSUE TITLE
[PE-D][Tester C] Course creation allows special characters

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T09-4/tp#113]
Differs from specification in the User Guide, which explicitly mentions:

> `COURSE_CODE` should be a string made up of alphabetical characters and numbers, with no special characters.

However, performing `course create course/!!!` and `course create course/!@#$%^&*()` results in the following:

![image.png](https://raw.githubusercontent.com/kiatkat/ped/main/files/9f9c1f4c-aaed-42f8-9679-6bde14567886.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: kiatkat/ped#3

**Comment by anthonytamzil** [comment]
Same issue as #109
