### ISSUE TITLE
[PE-D][Tester B] Edit Course: Able to edit to empty course name

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T09-4/tp#115]
I believer there isn't any validation for the course when editing. I could edit the name to empty and it will allow.

![Screenshot 2023-11-03 at 4.24.18 PM.png](https://raw.githubusercontent.com/devanshubisht/ped/main/files/9b55273d-c579-423d-8e97-2deb8b5acdae.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: devanshubisht/ped#4

**Comment by anthonytamzil** [comment]
Same issue as #109
