### ISSUE TITLE
[PE-D][Tester E] User Guide: Instruction repeated twice

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T09-4/tp#120]
Under `Adding a new contact` feature:

STUDENT_ID should be a string made up of alphanumeric characters, with no special characters or space.

is repeated.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: ruo-x/ped#2

**Comment by anthonytamzil** [comment]
same issue as #130
