### ISSUE TITLE
[PE-D][Tester B] Same name cannot be marked

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T09-4/tp#129]
If I have 2 people with the same name, I cannot mark the 2nd person. This is perhaps because ur identifier is id and not the name. And you are detecting math through name. Perhaps you can detect it through index instead.

![Screenshot 2023-11-03 at 4.39.58 PM.png](https://raw.githubusercontent.com/devanshubisht/ped/main/files/034db093-6748-4122-89cb-70aaea8c091a.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: devanshubisht/ped#9

**Comment by 0xteet0** [comment]
Mitigation of Feature Flaw:
- To be fixed by clearly stating limitations of current command in `UserGuide.md` with constraints, potential pitfall and workarounds etc.
- Place concept of enhancement under "Future Improvements for Features"
