### ISSUE TITLE
[PE-D][Tester C] Repeated functionality between `delete all` and `clear`

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T09-4/tp#136]
The command `delete all` (with no further parameters supplied) and `clear` seem to do the exact same thing. Perhaps the team should consider consolidating this functionality into one command, to avoid confusion in the user?

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: kiatkat/ped#6

**Comment by spatuly** [comment]
probably can remove one of the commands bc functionality is repeated
