### ISSUE TITLE
[PE-D][Tester B] List Attendance: Issue with specificity of error

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T09-4/tp#137]
Error is due to wrong prefix used and not the number being wrong.

![Screenshot 2023-11-03 at 4.55.50 PM.png](https://raw.githubusercontent.com/devanshubisht/ped/main/files/4dacfd71-4734-48a0-9473-02a7a0c6617d.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: devanshubisht/ped#13

**Comment by spatuly** [comment]
This is a recurring problem for all commands. When the user uses an invalid prefix, it recognises it as part of the input for the previous valid prefix and throws the error accordingly.
