### ISSUE TITLE
[PE-D][Tester E] Merge feature: don't fit well with the product

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T09-4/tp#143]
I am unsure of how this feature can come in handy as the chances of me wanting to merge 2 students is quite low, perhaps in the user guide, can consider adding tips on how it can be used to make managing contacts more efficient?

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ruo-x/ped#5

**Comment by fuyiqiao** [comment]
Planned Enhancement:
- We plan to implement importing student records from a csv file in future, which may create duplicated records. This would be where our merge command comes into play, merging duplicated records so that no information is lost.
